### "Index page"
GET http://localhost:8080/actuator

### Список бинов, созданных в приложении
GET http://localhost:8080/actuator/beans

### Информация о приложении
GET http://localhost:8080/actuator/info

### Все @ConfigurationProperties
GET http://localhost:8080/actuator/configprops

### Все перепенные окружения
GET http://localhost:8080/actuator/env

### Список логгеров
GET http://localhost:8080/actuator/loggers

### Конфигурация конкретного логгера
GET http://localhost:8080/actuator/loggers/org.springframework

### Изменение уровня логгирования в runtime
POST http://localhost:8080/actuator/loggers/org.springframework
Content-Type: application/json

{
  "configuredLevel": "TRACE"
}

### Healthchecks
GET http://localhost:8080/actuator/health

### Собственный healthcheck
GET http://localhost:8080/actuator/health/my

### Список метрик
GET http://localhost:8080/actuator/metrics

### Состояние подключений к БД
GET http://localhost:8080/actuator/metrics/hikaricp.connections.usage

### Загрузка CPU приложением
GET http://localhost:8080/actuator/metrics/process.cpu.usage

### Используемая JVM память
GET http://localhost:8080/actuator/metrics/jvm.memory.used

### Получение данных о запросах
# Дополнительно можно настроить SLA, персентили и т.д.
# причём для отдельных запросов
GET http://localhost:8080/actuator/metrics/http.server.requests

### А вот все метрики для Promehteus
GET http://localhost:8080/actuator/prometheus


### Spring Data REST - Single entity
GET http://localhost:8080/person/40

### Spring Data REST - Collection
GET http://localhost:8080/person

### Add Alex
POST http://localhost:8080/person
Content-Type: application/json

{
  "name": "Alex"
}

### Rename Ivan
PATCH http://localhost:8080/person/1
Content-Type: application/json

{
  "name": "Anton"
}

###
