spring:
  data:
    mongodb:
      port: 0
      database: words
      embedded:
        version: 4.0.21

mongock:
  runner-type: "ApplicationRunner" # default
  change-logs-scan-package:
    - com.example.homework11_webflux.mongock.changelog
  mongo-db:
    write-concern:
      journal: false
    read-concern: local

logging:
  level:
    root: ERROR
