server:
  port: 9090
spring:
  datasource:
    initialization-mode: always

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: false

  rabbitmq:
    addresses: "192.168.99.100"