spring:
  datasource:
    url: jdbc:h2:mem:testdb
    initialization-mode: always
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: false
    show-sql: true

