spring:
  main:
    allow-circular-references: true
  banner:
    location: classpath:banner.txt
  datasource:
    url: jdbc:h2:mem:testdb
  sql:
    init:
      mode: always
      data-locations: db/data.sql
      schema-locations: db/schema.sql
  h2:
    console:
      path: /h2-console
      settings:
        web-allow-others: true
      enabled: true
