drop table IF EXISTS BOOKS;
create TABLE BOOKS(
ID BIGINT PRIMARY KEY auto_increment,
  NAME        VARCHAR(255),
  DESCRIPTION VARCHAR(1000),
  AUTHOR_ID   BIGINT,
  GENRE_ID    BIGINT);

drop table IF EXISTS AUTHORS;
create TABLE AUTHORS(
ID BIGINT PRIMARY KEY auto_increment,
  NAME        VARCHAR(255),
  BIRTH_YAR   DATE,
  DESCRIPTION VARCHAR(1000));

drop table IF EXISTS GENRES;
create TABLE GENRES(
ID BIGINT PRIMARY KEY auto_increment,
  NAME VARCHAR(255));

drop table IF EXISTS COMMENTS;
create table comments(
ID BIGINT PRIMARY KEY auto_increment,
    BOOK_ID BIGINT references BOOKS(id) on delete cascade,
    text VARCHAR(4000));

drop table IF EXISTS USERS;
create TABLE USERS(
ID BIGINT PRIMARY KEY auto_increment,
  USERNAME VARCHAR(255),
  PASSWORD VARCHAR(100),
  NONEXPIRED TINYINT NOT NULL,
  NONLOCKED TINYINT NOT NULL,
  CREDENTIALSNONEXPIRED TINYINT NOT NULL,
  ENABLED TINYINT NOT NULL DEFAULT 1,
  UNIQUE KEY UK_USERNAME (USERNAME)
  );

drop table IF EXISTS USER_AUTHORITIES;
CREATE TABLE USER_AUTHORITIES (
ID BIGINT PRIMARY KEY auto_increment,
    USERNAME varchar(255) NOT NULL,
    AUTHORITY varchar(45) NOT NULL,
    UNIQUE KEY UK_USERNAMEROLE (USERNAME,AUTHORITY)
    );