create table person (
    id integer generated by default as identity,
    name varchar(255),
    hobby varchar(500),
    primary key (id)
);

create table person_hobby (
    person_id integer references person(id),
    hobby varchar(255)
);