spring:
  messages:
    basename: bundle

  shell:
    interactive:
      enabled: true

  datasource:
    url: jdbc:h2:mem:testdb
    initialization-mode: always

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: false

application:
  version: 1.0
  locale: en_EN