DROP TABLE IF EXISTS BOOKS CASCADE;
DROP TABLE IF EXISTS AUTHORS;
DROP TABLE IF EXISTS GENRES;
DROP TABLE IF EXISTS COMMENTS;

DROP SEQUENCE IF EXISTS book_id_seq;
DROP SEQUENCE IF EXISTS author_id_seq;
DROP SEQUENCE IF EXISTS genre_id_seq;
DROP SEQUENCE IF EXISTS comment_id_seq;

CREATE SEQUENCE book_id_seq START WITH 1;
CREATE SEQUENCE author_id_seq START WITH 1;
CREATE SEQUENCE genre_id_seq START WITH 1;
CREATE SEQUENCE comment_id_seq START WITH 1;

CREATE TABLE AUTHORS
(
    ID   BIGSERIAL,
    NAME VARCHAR(255) NOT NULL,
    CONSTRAINT authors_pkey PRIMARY KEY (id)
);

CREATE TABLE GENRES
(
    ID  bigserial,
    NAME VARCHAR(255) NOT NULL,
    CONSTRAINT genres_pkey PRIMARY KEY (id)
);

CREATE TABLE BOOKS
(
    ID        BIGSERIAL,
    TITLE      VARCHAR(255) NOT NULL,
    AUTHOR_ID BIGINT       REFERENCES authors (ID),
    GENRE_ID  BIGINT       REFERENCES genres (ID),
    CONSTRAINT books_pkey PRIMARY KEY (ID)
--     CONSTRAINT books_author_id_fkey FOREIGN KEY (AUTHOR_ID)
--         ,
--     CONSTRAINT books_genre_id_fkey FOREIGN KEY (GENRE_ID)

);

CREATE TABLE COMMENTS
(
    ID   BIGSERIAL,
    BOOK_ID BIGINT    REFERENCES BOOKS (ID) ON DELETE cascade,
    TEXT VARCHAR(255) NOT NULL,
    USER_NAME VARCHAR(255) NOT NULL,
    CONSTRAINT comments_pkey PRIMARY KEY (id)
);





