DROP TABLE IF EXISTS AUTHOR;
CREATE TABLE AUTHOR(ID BIGINT PRIMARY KEY AUTO_INCREMENT, NAME VARCHAR(255));

DROP TABLE IF EXISTS GENRE;
CREATE TABLE GENRE(ID BIGINT PRIMARY KEY AUTO_INCREMENT, NAME VARCHAR(255));

DROP TABLE IF EXISTS BOOK;
CREATE TABLE BOOK(ID BIGINT PRIMARY KEY AUTO_INCREMENT, NAME VARCHAR(255));

DROP TABLE IF EXISTS BOOK_AUTHOR_LINK;
CREATE TABLE BOOK_AUTHOR_LINK(ID BIGINT PRIMARY KEY AUTO_INCREMENT, BOOK_ID BIGINT, AUTHOR_ID BIGINT);

DROP TABLE IF EXISTS BOOK_GENRE_LINK;
CREATE TABLE BOOK_GENRE_LINK(ID BIGINT PRIMARY KEY AUTO_INCREMENT, BOOK_ID BIGINT, GENRE_ID BIGINT);