spring:
  application:
    name: service-order
    instance_id: i0
  cloud:
    config:
      fail-fast: true
      retry:
        initial-interval: 5000
        max-attempts: 10
        max-interval: 5000
        multiplier: 1.2
  config:
    import: optional:configserver:http://localhost:8888
  codec:
    max-in-memory-size: 10MB


