insert into app_users(name, email) values ('Рафаель Губерманович Тыгыдым', 'test@mail.ru')
insert into app_users(name, email) values ('Артем Демосфенович Шмяк', 'test@mail.ru')
insert into app_users(name, email) values ('Ифигения Бореславовна Фуфелшмерц', 'test@mail.ru')

insert into activity_types(name) values ('Очень полезное дело №4')
insert into activity_types(name) values ('Очень полезное дело №13')
insert into activity_types(name) values ('Очень полезное дело №34')
insert into activity_types(name) values ('Очень полезное дело №48')
insert into activity_types(name) values ('Очень полезное дело №53')
insert into activity_types(name) values ('Вредное дело №11')
insert into activity_types(name) values ('Вредное дело №12')
insert into activity_types(name) values ('Вредное дело №13')
insert into activity_types(name) values ('Вредное дело №14')
insert into activity_types(name) values ('Вредное дело №15')
insert into activity_types(name) values ('Вредное дело №16')

