###
GET http://localhost:8080/flux/one
Accept: */*
Content-Type: application/json
Cache-Control: no-cache

###
GET http://localhost:8080/flux/three
Accept: */*
Content-Type: application/json
Cache-Control: no-cache

###
GET http://localhost:8080/flux/ten
Accept: */*
Content-Type: application/json
Cache-Control: no-cache

###
GET http://localhost:8080/flux/stream
Accept: */*
Content-Type: application/json
Cache-Control: no-cache

###
GET http://localhost:8080/rx/one
Accept: */*
Content-Type: application/json
Cache-Control: no-cache

###
GET http://localhost:8080/rx/ten
Accept: */*
Content-Type: application/json
Cache-Control: no-cache

###
GET http://localhost:8080/rx/five
Accept: */*
Content-Type: application/json
Cache-Control: no-cache