spring:
  batch:
    job:
      enabled: false
  shell:
    interactive:
      enabled: true

  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  data:
    mongodb:
      uri: mongodb://localhost
      port: 0 #27017
      database: SpringBatchExampleDB

app:
  ages-count-to-add: 1
  input-file: entries.csv
  output-file: output.dat

#debug: true
