spring:
  data:
    mongodb:
      uri: "mongodb+srv://mongo_user_mank_1:12345@cluster0.tsbgv.mongodb.net/company?retryWrites=true&w=majority"
#      username: mongo_user_mank_1
#      password: 12345
      database: company

mongock:
  runner-type: "ApplicationRunner" # default
  #runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.otus.spring.mongock.changelog

