DROP TABLE IF EXISTS BOOKS CASCADE;
DROP TABLE IF EXISTS AUTHORS;
DROP TABLE IF EXISTS GENRES;

DROP SEQUENCE IF EXISTS book_id_seq;
DROP SEQUENCE IF EXISTS author_id_seq;
DROP SEQUENCE IF EXISTS genre_id_seq;

CREATE SEQUENCE book_id_seq START WITH 1;
CREATE SEQUENCE author_id_seq START WITH 1;
CREATE SEQUENCE genre_id_seq START WITH 1;;

CREATE TABLE AUTHORS
(
    ID   BIGINT DEFAULT NEXTVAL('author_id_seq') NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    CONSTRAINT "Authors_pkey" PRIMARY KEY (id)
);

CREATE TABLE GENRES
(
    ID   BIGINT       NOT NULL DEFAULT nextval('genre_id_seq'),
    NAME VARCHAR(255) NOT NULL,
    CONSTRAINT genres_pkey PRIMARY KEY (id)
);

CREATE TABLE BOOKS
(
    ID        BIGINT       NOT NULL DEFAULT nextval('book_id_seq'),
    NAME      VARCHAR(255) NOT NULL,
    AUTHOR_ID BIGINT       NOT NULL,
    GENRE_ID  BIGINT       NOT NULL,
    CONSTRAINT books_pkey PRIMARY KEY (ID),
    CONSTRAINT books_author_id_fkey FOREIGN KEY (AUTHOR_ID)
        REFERENCES authors (ID),
    CONSTRAINT books_genre_id_fkey FOREIGN KEY (GENRE_ID)
        REFERENCES genres (ID)
);




