version: '2'
services:
  dockerhost:
    image: qoomon/docker-host
    cap_add: [ 'NET_ADMIN', 'NET_RAW' ]
    mem_limit: 4M
    restart: on-failure
  camunda:
    image: camunda/camunda-bpm-platform:latest
    ports:
      - 8181:8080
    environment:
      - DB_DRIVER=org.postgresql.Driver
      - DB_URL=jdbc:postgresql://postgres:5432/process-engine
      - DB_USERNAME=camunda
      - DB_PASSWORD=camunda
      - WAIT_FOR=postgres:5432
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=camunda
      - POSTGRES_PASSWORD=camunda
      - POSTGRES_DB=process-engine
    volumes:
      - my_dbdata:/var/lib/postgresql/data
volumes:
  my_dbdata:
