management:
  tracing:
    sampling:
      probability: 1.0
  endpoint:
    prometheus:
      enabled: true
    metrics:
      enabled: true
    health:
      enabled: true
      probes:
        enabled: true
    refresh:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
          - prometheus
          - health
          - metrics
          - refresh
    enabled-by-default: false
  metrics:
    tags:
      application: ${spring.application.name}

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9999/eureka/
  instance:
    lease-renewal-interval-in-seconds: 30
    metadataMap:
      zone: zone1