spring:

  liquibase:
    change-log: classpath:db/changelog/structure.xml

  datasource:
    url: jdbc:postgresql://192.168.99.100/patients_db
    username: admin
    password: 123456
    driver-class-name: org.postgresql.Driver

  messages:
    basename: bundle

server:
  port: 8086

  jpa:
    generate-ddl: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate.format_sql: true

application:
  name: project
  version: 1.0
  locale: ru_RU

mail:
  username:
  password:
  host: smtp.mail.ru
  port: 465

debug: false