spring:

  datasource:
    url: jdbc:h2:mem:testdb
    initialization-mode: always

  liquibase:
    change-log: classpath:db/changelog/structure.xml

  messages:
    basename: bundle

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate.format_sql: true

application:
  version: 1.0
  locale: en_EN
  security: false

mail:
  username: none
  password: none
  host: smtp.mail.ru
  port: 465
