INSERT INTO USERS (ID, USERNAME, NAME, PASSWORD, NONEXPIRED, NONLOCKED, CREDENTIALSNONEXPIRED, ENABLED, DESCRIPTION, EMAIL, TEL) VALUES
(1,	'admin',	'admin',	'111',	1,	1,	1,	1,	'',	'mr@bk.ru',	'1234544');

INSERT INTO USER_AUTHORITIES (ID, USERNAME, AUTHORITY) VALUES
(1,	'admin',	'ROLE_DOC');