drop table IF EXISTS USERS;
create TABLE USERS(
  ID SERIAL,
  USERNAME VARCHAR(255),
  NAME VARCHAR(255),
  PASSWORD VARCHAR(100),
  NONEXPIRED INT NOT NULL,
  NONLOCKED INT NOT NULL,
  CREDENTIALSNONEXPIRED INT NOT NULL,
  ENABLED INT NOT NULL DEFAULT 1,
  DESCRIPTION VARCHAR(255),
  EMAIL VARCHAR(255),
  TEL VARCHAR(255)
  );

drop table IF EXISTS USER_AUTHORITIES;
CREATE TABLE USER_AUTHORITIES (
  ID SERIAL,
  USERNAME varchar(255) NOT NULL,
  AUTHORITY varchar(45) NOT NULL
  );

drop table IF EXISTS CHECKLIST;
CREATE TABLE CHECKLIST (
  ID SERIAL,
  USERID bigint NOT NULL,
  DAYNUMBER INT,
  NONSYMPTOMS INT, -- Симптомов нет
  FEVER INT, -- Лихорадка
  SORETHROAT INT, -- Боль в горле
  COUGH INT, -- Кашель
  RUNNYNOSE INT, -- Насморк
  DYSPNEA INT, -- Одышка
  OTHERSYMPTOMS VARCHAR(255)
  );