spring:
  banner:
    location: classpath:banner.txt

  messages:
    encoding: UTF-8

  data:
    mongodb:
      database: library

  mongodb:
    embedded:
      version: 5.0.6

mongock:
  mongo-db:
    write-concern:
      journal: false
  runner-type: InitializingBean
  change-logs-scan-package:
    - ru.otus.spring.mongock.changelog

logging:
  level:
    ROOT: ERROR
