###
GET http://localhost:8080/data-mono/13
Accept: */*
Content-Type: application/json
Cache-Control: no-cache


###
GET http://localhost:8080/data/5
Accept: */*
Content-Type: application/json
Cache-Control: no-cache