DROP TABLE IF EXISTS `books_authors`;
DROP TABLE IF EXISTS `books_genres`;

DROP TABLE IF EXISTS `authors`;
CREATE TABLE `authors`(
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(255) NOT NULL,
    PRIMARY KEY(`id`)
) DEFAULT CHARACTER SET 'UTF8';

DROP TABLE IF EXISTS `books`;
CREATE TABLE `books`(
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `caption` VARCHAR(255) NOT NULL,
    PRIMARY KEY(`id`)
) DEFAULT CHARACTER SET 'UTF8';

DROP TABLE IF EXISTS `genres`;
CREATE TABLE `genres`(
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(255) NOT NULL,
    PRIMARY KEY(`id`)
) DEFAULT CHARACTER SET 'UTF8';

CREATE TABLE `books_authors`(
    `book_id` BIGINT NOT NULL,
    `author_id` BIGINT NOT NULL,
    FOREIGN KEY (`book_id`) REFERENCES `books`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (`author_id`) REFERENCES `authors`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE `books_genres`(
    `book_id` BIGINT NOT NULL,
    `genre_id` BIGINT NOT NULL,
    FOREIGN KEY (`book_id`) REFERENCES `books`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (`genre_id`) REFERENCES `genres`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
);
