greetings:
  first-greeting: Привет
  re-greeting: Рад снова тебя видеть


condition:
  alexey-exists: true
  yanis-exists: false

spring:
  profiles:
    #active: Oleg
    #active: Peter

logging:
  level:
    root: ERROR


---
spring:
  profiles: Peter

condition:
  yanis-exists: true
